// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Edge struct {
	Label  string `json:"label"`
	Source string `json:"source"`
	Target string `json:"target"`
}

type GraphFull struct {
	Nodes []*Node `json:"nodes"`
	Edges []*Edge `json:"edges"`
}

type GraphSlim struct {
	Nodes []string `json:"nodes,omitempty"`
	Edges []*Edge  `json:"edges,omitempty"`
}

type Mutation struct {
}

type Node struct {
	ID   string  `json:"id"`
	Text string  `json:"text"`
	X    float64 `json:"x"`
	Y    float64 `json:"y"`
}

type NodeCreate struct {
	Text string  `json:"text"`
	X    float64 `json:"x"`
	Y    float64 `json:"y"`
}

type NodeUpdate struct {
	Text *string  `json:"text,omitempty"`
	X    *float64 `json:"x,omitempty"`
	Y    *float64 `json:"y,omitempty"`
}

type Query struct {
}
